### PR TITLE
add support for macos build

### PR DESCRIPTION
**Pull request by LeeTeng2001**
- Added gl3w binaries for apple
- modified some SDL code to query actual drawable size of window for retina display
- Added build instruction for mac
- Updated gitignore to ignore macos and jetbrian ide junks

### CODE REVIEW

**Comment by LeeTeng2001** [comment]
Can you build on Windows once more to make sure it's working?

**Comment by LeeTeng2001** [comment]
fix #74

**Comment by LeeTeng2001** [comment]
Working examples on MacOS

Screenshot 2022-12-22 at 9 16 25 AM
Screenshot 2022-12-22 at 9 16 55 AM

**Comment by knightcrawler25** [comment]
This works perfectly :) Thanks a lot!

**Pull request merged**
