### PR TITLE
sdl2+gl3w+emscripten

### PR DESCRIPTION
**Pull request by CedricGuillemet**
Hi
I've changed glfw to SDL2 in order to compile for the web using emscripten.
a couple changes here and there and I'm really close to get it linking.
Thing is GL_TEXTURE_BUFFER/glTexBuffer is unsupported with webgl (such a shame)
Is it a lot of work to replace that with GL_TEXTURE_1D/2D?

### CODE REVIEW

**Comment by knightcrawler25** [comment]
Sorry for the long delay, I took some time out over the weekend and replaced everything with GL_TEXTURE_2D/1D and made some other changes:

- Replaced the BVH builder with code from RadeonRays. This is faster and code is cleaner than the old one.
- Support for instancing
- Added a simple API for loading the scene (This still needs a lot of work)
- Mix of Progressive and Tiled mode. This vastly improved interactivity by rendering a single tile every frame and switching to progressive when the camera moves. Link to a video: https://youtu.be/cGZUB9Q8wn8
- Works reasonably well for large models. For example the model in the screenshot below has 2M triangles and still works without any stalls

panther-scan

My concern is that I'm currently packing and unpacking BVH/triangle indices in a single int using bitwise operators but I'm not sure if that is supported in WebGL 1.0 and might require WebGL 2.0 for it to work. I am still cleaning up the test code and if support for bitwise operators is not an issue then I can add everything into a new branch. If not, I would need to figure out a different way to store the data in the textures without bloating it up.

**Comment by CedricGuillemet** [comment]
That's amazing! I can help you doing a clean API in order to plug anything as a scene loader.
My goal is to make it a standalone library. so you can use it from JavaScript to c++. Link with the library, load gltf. even tweak the scene (using a gizmo and some properties) and see the result in the browser.
Did you commit your change on texture 2D/1D? 
Webgl1 will be too much of a burden. Many browsers are still webgl1 but it's too difficult to port back the shaders.

**Comment by knightcrawler25** [comment]
Thanks a lot for all the help :) I didn't commit the changes in yet, but will do it in a day or two as I don't have access to my code right now.

**Comment by knightcrawler25** [comment]
I've merged your code along with my changes into the emscripten branch. Could you have a look and let me know if everything looks alright or if you see any issues. Also, i'll be adding any future changes to this branch and eventually when everything looks right, merge into master.

**Comment by CedricGuillemet** [comment]
Awesome!! I'm testing that today!

**Pull request merged**
