### PR TITLE
emscripten

### PR DESCRIPTION
**Pull request by CedricGuillemet**
I'm still trying to render everything in a browser thanks to emscripten.
I removed gl_texture_1d as it's not supported. Works fine on Windows.
I got an issue with too many textures used (17 textures! max is 16). I removed the uv for my tests with the Cornell box.
few fixes here and there.
For now, I get a violent webgl crash that I'm trying to fix. If you can limit the number of textures, that would be awesone! :)

### CODE REVIEW

**Comment by CedricGuillemet** [comment]
A quick test with a glsl 'denoiser'. Not a real one but fits in the outputfrag. Half right of screen is denoised.
image

**Comment by knightcrawler25** [comment]
Sure, i'll try and put all the mesh data into a single texture to get rid of all the indices and probably even the combine the bvh data into a single texture.

**Comment by CedricGuillemet** [comment]
Is it possible to update the scene BVH independently of the meshes/objects? I mean is it possible to change a mesh matrix, only update the scene bvh while having the meshes bvh unchanged?

**Comment by knightcrawler25** [comment]
It should be possible and that's how I was planning on handling scene changes. Right now it is only built once, but with a few changes, it should be possible to rebuild the scene bvh and replace a certain part of the bvh texture with the new data.

**Comment by knightcrawler25** [comment]
The noise function needs to change. I don't remember where I got the code from but it's not really good for convergence either. I was thinking of trying this out: https://www.shadertoy.com/view/3tB3z3

**Comment by knightcrawler25** [comment]
I reduced the number of textures from 17 to 13 for now. Will see if I can get rid of some more

**Comment by CedricGuillemet** [comment]
Sweet! Thank you! I'm back at debugging webgl...

**Pull request merged**
